server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

settings:
   stores:
        - store:
          - url: https://www.dns-shop.ru
            name: DNS
            categories:
              - name: Техника
        - store:
            - url: https://www.ozon.ru/
              name: OZON
              categories:
                - name: Техника
                - name: Одежда
                - name: Книги
                - name: Мебель