server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

settings:
    stores:
      - store:
        url: https://www.ozon.ru
        name: OZON
        categories:
          - electronics
          - clothing
          - footwear
          - furniture
          - books
      - store:
        url: https://market.yandex.ru
        name: Яндекс Маркет
        categories:
          - electronics
          - clothing
          - footwear
          - furniture
          - books
      - store:
        url: https://www.wildberries.ru/
        name: Wildberries
        categories:
          - electronics
          - clothing
          - footwear
          - furniture
          - books
      - store:
        url: https://www.dns-shop.ru
        name: DNS
        categories:
          - electronics
          - furniture
      - store:
        url: https://www.mvideo.ru/
        name: М-Видео
        categories:
          - electronics
          - furniture
      - store:
        url: https://www.citilink.ru/
        name: Ситилинк
        categories:
          - electronics
          - furniture
      - store:
        url: https://www.lamoda.ru/
        name: lamoda
        categories:
          - clothing
          - footwear
      - store:
        url: https://www.litres.ru/
        name: Литрес
        categories:
          - books